fix: handle `CORS` errors in `checkUrl`
innovation-system/electron-kiosk pull request #6
Opened 2023-03-09 09:40 UTC by reekoz

Fixes #5

2023-03-09 09:52 UTC, robertsLando requested changes

2023-03-11 08:30 UTC, robertsLando commented
@reekoz Ping

2023-03-13 07:43 UTC, reekoz commented
What I should do? I can rollback `package.json` changes

2023-03-13 07:49 UTC, reekoz commented
@robertsLando I've rolled back version

2023-03-13 08:14 UTC, robertsLando approved these changes

2023-03-13 08:14 UTC, merged